--- 
- 
  become: true
  hosts: svi
  tasks: 
    - 
      name: "uradi u name"
      shell: "uname -a > /home/ansible/ansible/rezultat.txt"
    - 
      name: whoami
      shell: "whoami >> /home/ansible/ansible/rezultat.txt"


